import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, map, of } from 'rxjs';

import { environment } from '../../environments/environment';

/**
 * News-archive candidates.
 *
 * Every other question in the bank is generated by rule from a dataset. These
 * are the exception: an article said something happened, and a person has to
 * read the sentence and write the question. The service exists to keep that
 * pairing intact — the sentence and the link travel together, and the write
 * call sends only wording, never a citation.
 */

export interface NarrativeCandidate {
  mmdd: string;
  yearEventId: string;
  gameId: string;
  eventDate: string;
  year: number;
  league: string;
  headline: string;
  citedSentence: string;
  publishedAt?: string;
  sourceName: string;
  sourceDatasetRef: string;
  candidateScore?: number;
  usable: boolean;
  status: string;
}

export interface NarrativeDraft {
  type: 'mc' | 'clue' | 'numeric';
  prompt: string;
  answer: string | number;
  distractors?: string[];
  clues?: string[];
  tolerance?: number;
  tier?: number;
}

@Injectable({ providedIn: 'root' })
export class NarrativeService {
  constructor(private readonly http: HttpClient) {}

  private get preview(): boolean {
    return environment.useLocalSample;
  }

  list(status = 'needs_review', limit = 50): Observable<NarrativeCandidate[]> {
    if (this.preview) return of([]);
    const params = new URLSearchParams({ status, limit: String(limit) });
    return this.http
      .get<{ candidates: NarrativeCandidate[] }>(
        `${environment.apiBase}/admin/narrative?${params.toString()}`,
      )
      .pipe(map((r) => r.candidates ?? []));
  }

  /**
   * Write a question from a candidate.
   *
   * Only the identity of the candidate and the wording go over the wire. The
   * cited sentence and the source link are read server-side from the candidate
   * itself, so nothing here can point a question at a source it did not come
   * from.
   */
  write(candidate: NarrativeCandidate, fields: NarrativeDraft): Observable<unknown> {
    return this.http.post(`${environment.apiBase}/admin/narrative-write`, {
      action: 'write',
      mmdd: candidate.mmdd,
      yearEventId: candidate.yearEventId,
      fields,
    });
  }

  discard(candidate: NarrativeCandidate, note?: string): Observable<unknown> {
    return this.http.post(`${environment.apiBase}/admin/narrative-write`, {
      action: 'discard',
      mmdd: candidate.mmdd,
      yearEventId: candidate.yearEventId,
      note,
    });
  }
}
